### ISSUE TITLE
Allow incorporation into other tools

### ISSUE THREAD

**Issue by deanrad** [East5th/package-scan#2]
- Expose an API to get the errors 
- Also, server-side HTTP.call does not require a callback (https://github.com/East5th/package-scan/blob/master/lib/package-scan.js#L37)

I may work on a PR for this when I can..

**Comment by pcorey** [comment]
Good idea with an API. Currently, scan.east5th.co is just serving a static site. I may want to turn this into a proper web app that also serves the data over a REST (or maybe DDP?) API. I'll throw that on my radar.

Good call with `HTTP.call` on the server. It's hard getting out of the callback-everywhere habit.
