### ISSUE TITLE
Error on project start 1.4.1.1 on windows

### ISSUE THREAD

**Issue by fafournier** [East5th/package-scan#5]
Hi, the package seems to generate an error on the last version of meteor on windows. it took quite a while to isolate but this package seems to be the only difference on my project between it running and not. 

```
 events.js:141
       throw er; // Unhandled 'error' event
       ^
 Error: ENOENT: no such file or directory, open C:\Users\user\projects\project\.meteor\local\build\programs\server\undefined\.meteor\versions'
    at Error (native)
```

I suspect the problem comes from lib/package-scan.js: 59   where it's specified var path = process.env.PWD + '/.meteor/versions'; 
somehow, the process.env.PWD must not be correct anymore. I, however have not had the time to look what it should be replaced by so far...

**Comment by pcorey** [comment]
Good catch @fafournier. I'll try to take a look into this and get a fix pushed out.

**Comment by alesn** [comment]
I am not sure if this was previously resolved but the exact same problem occurred now, when I added this package to a Meteor project on Windows 10 and Meteor 1.6.1

**Comment by pcorey** [comment]
Thanks @alesn. I'll get my hands on a windows machine/VM and try to recreate this.

**Comment by andsnw** [comment]
Exact same error reproduced on Windows 10, Meteor 1.7.0.5.

EDIT:
Wrote a quick fix - https://github.com/East5th/package-scan/pull/7

**Comment by pcorey** [comment]
Thanks @andsnw!
